### ISSUE TITLE
网站提交

### ISSUE THREAD

**Issue by dangpf** [jaywcjlove/FED#10]
{
// 必填－名字
"name":"菜鸟教程", 
// 必填－网址
"url":"http://www.runoob.com/", 
// 选填－图标
"ico":"http://www.runoob.com/favicon.ico",
// 必填－可以留空 － 描述说明
"des":"" ,
// 选填－标签，便于归类
"tags":["社区","工具"]
}

**Comment by jaywcjlove** [comment]
已经添加了 @dangpf
