### ISSUE TITLE
网站提交

### ISSUE THREAD

**Issue by zhuyingda** [jaywcjlove/FED#3]
{
    // 必填－名字
    "name":"朱英达的个人博客", 
    // 必填－网址
    "url":"https://www.zhuyingda.com/", 
    // 选填－图标
    "ico":"https://www.zhuyingda.com/favicon.ico",
    // 必填－可以留空 － 描述说明
    "des":"技术博客，有关web的安全问题和性能问题" ,
    // 选填－标签，便于归类
    "tags":["技术","博客","安全"]
}

**Comment by jaywcjlove** [comment]
@zhuyingda  已经添加

**Comment by dangpf** [comment]
{
// 必填－名字
"name":"菜鸟教程", 
// 必填－网址
"url":"http://www.runoob.com/", 
// 选填－图标
"ico":"http://www.runoob.com/favicon.ico",
// 必填－可以留空 － 描述说明
"des":"" ,
// 选填－标签，便于归类
"tags":["社区","工具"]
}

**Comment by dangpf** [comment]
网站提交
