### ISSUE TITLE
网址提交

### ISSUE THREAD

**Issue by mumuy** [jaywcjlove/FED#30]
{
    // 必填－名字
    "name":"路人甲", 
    // 必填－网址
    "url":"http://passer-by.com/", 
    // 选填－图标
    "ico":"http://passer-by.com/public/image/favicon.png",
    // 必填－可以留空 － 描述说明
    "des":"jQuery插件库，js算法等" ,
    // 选填－标签，便于归类
    "tags":["插件","算法"]
}

**Comment by jaywcjlove** [comment]
@mumuy  已添加

**Comment by 2596887568** [comment]
{
// 必填－名字
"name":"汇智网", 
// 必填－网址
"url":"http://www.hubwiz.com/", 
// 选填－图标
"ico":"",
// 必填－可以留空 － 描述说明
"des":"一家免费的在线互动式编程网站" ,
// 选填－标签，便于归类
"tags":["编程","node.js","angular.js","js","mongodb","vue.js","react","nginx"]
}

**Comment by jaywcjlove** [comment]
@2596887568   添加了...

**Comment by 2596887568** [comment]
多谢，方便的话加个友链？加个qq？ @jaywcjlove
