### ISSUE TITLE
一个前端资源整合网站

### ISSUE THREAD

**Issue by zanqianqvxifu** [jaywcjlove/FED#54]
f2er.club

**Comment by showonne** [comment]
这个我很早的时候提过了，很好的site。

**Comment by jaywcjlove** [comment]
@zanqianqvxifu @showonne  早已经添加了之前不叫 [醉牛前端](http://jsdig.com/?kw=%E5%89%8D%E7%AB%AF%E4%BA%BA%E7%9A%84%E4%BF%B1%E4%B9%90%E9%83%A8) 你们点击进去看看
