### ISSUE TITLE
假设内容量非常大，加载时间比较长，是否有解决方法

### ISSUE THREAD

**Issue by xuelainiao** [jaywcjlove/FED#67]
我测试了一个3w条的数据，利用你提供的代码，不过似乎刚开始加载起来时间非常长，是否有好的办法压缩这个时间，谢谢！

**Comment by jaywcjlove** [comment]
@xuelainiao 😆 求star

下面优化方向：

1. 可以弄个索引 数据文件，去掉`详情`搜索匹配，只匹配标题
2. 根据索引到的数据去请求详情数据

`3w`条数据也不是特别多，分10个json 文件把数据请求出来，进行合并。

> 这个是静态的总归不是什么好的解决方案，建议走数据库。
