### ISSUE TITLE
如果json有几万条信息的话反应有些慢

### ISSUE THREAD

**Issue by xuelainiao** [jaywcjlove/FED#68]
求个解决思路

**Comment by jaywcjlove** [comment]
@xuelainiao 方法不是告诉你了，

1. 去掉检索内容，只检索标题，不检索详情。
2. 输入搜搜匹配是正则，看看正则有优化空间没有
3. 如果数据load得有点慢，json文件分多个文件加载

⚠️ 这个不是处理“大数据”的。

**Comment by xuelainiao** [comment]
sorry，应该是发送到哪里 没看到... 实在抱歉
