### ISSUE TITLE
请问首页 js 引用上的时间戳是怎么加上的呢？

### ISSUE THREAD

**Issue by SuperRay3** [jaywcjlove/FED#70]
<script type="text/javascript" src="js/index.min.js?d=1460130981801"></script>

后面的时间戳是工具生成的吗？ 为什么不会变化～ 求解答。

**Comment by jaywcjlove** [comment]
@SuperRay3 手工加上去的😆

**Comment by SuperRay3** [comment]
@jaywcjlove 那这样做有什么作用呢？

**Comment by jaywcjlove** [comment]
@SuperRay3 因此每次更改了js文件后，如果你之前访问过，客户端会读缓存js文件，增加个参数，客户端浏览器就会重新下载新的js文件 ，刷新缓存的作用。

用webpack打包就不会出现这种问题，因为引入js 文件名是哈希命名的。

![image](https://user-images.githubusercontent.com/1680273/38227340-52d1aada-3730-11e8-829a-70a7b148c35b.png)
