### ISSUE TITLE
网站挂了

### ISSUE THREAD

**Issue by hiyangguo** [jaywcjlove/FED#92]
[http://jsdig.com/](http://jsdig.com/)

![image](https://user-images.githubusercontent.com/15609339/116507990-fb80b400-a8f2-11eb-95dc-548b143b5d5c.png)

404 了

**Comment by hiyangguo** [comment]
我镜像了一个 
https://fed.hiyangguo.com/

**Comment by jaywcjlove** [comment]
@hiyangguo 域名忘记续费了。https://jaywcjlove.github.io/FED

**Comment by hiyangguo** [comment]
> @hiyangguo 域名忘记续费了。https://jaywcjlove.github.io/FED

😂
